:source-highlighter: prettify

// Broker Package Directories
//  slack-broker-spring-boot
:broker-basedir: ../../broker/slack-broker-spring-boot/src/main/kotlin/io/olaph/slack/broker/
:broker-broker: {broker-basedir}/broker/
:broker-configuration: {broker-basedir}/configuration/
:broker-exception: {broker-basedir}/exception/
:broker-receiver: {broker-basedir}/receiver/

//  slack-broker-spring-boot-autoconfigure
:autoconfig-basedir: ../../broker/slack-broker-spring-boot-autoconfigure/src/main/kotlin/io/olaph/slack/broker/autoconfiguration/

// Client Package Directories
//  slack-api-client
:slack-api-client-basedir:          ../../client/slack-api-client/src/main/kotlin/io/olaph/slack/client/
:client-groups:                     {slack-api-client-basedir}/group/

:group-auth:                        {client-groups}/auth/
:group-channels:                    {client-groups}/channels/
:group-chat:                        {client-groups}/chat/
:group-conversations:               {client-groups}/conversations/
:group-dialog:                      {client-groups}/dialog/
:group-im:                          {client-groups}/im/
:group-oauth:                       {client-groups}/oauth/
:group-users:                       {client-groups}/users/

//  slack-spring-api-client
:slack-spring-api-client-basedir:   ../../client/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/
:implementation:                    {slack-spring-api-client-basedir}/implementation/
:implementation-group:              {implementation}/group/

:impl-group-auth:                   {implementation-group}/auth/
:impl-group-channels:               {implementation-group}/channels/
:impl-group-chat:                   {implementation-group}/chat/
:impl-group-conversations:          {implementation-group}/conversations/
:impl-group-dialog:                 {implementation-group}/dialog/
:impl-group-im:                     {implementation-group}/im/
:impl-group-oauth:                  {implementation-group}/oauth/
:impl-group-users:                  {implementation-group}/users/

//  slack-spring-test-api-client
:test-api-client-basedir:           ../../client/slack-spring-test-api-client/src/main/kotlin/io/olaph/slack/client/test/
:test-api-client-group:             {test-api-client-basedir}/group/

:test-group-auth:                   {test-api-client-group}/auth/
:test-group-channel:                {test-api-client-group}/channel/
:test-group-chat:                   {test-api-client-group}/chat/
:test-group-conversation:           {test-api-client-group}/conversation/
:test-group-dialog:                 {test-api-client-group}/dialog/
:test-group-im:                     {test-api-client-group}/im/
:test-group-oauth:                  {test-api-client-group}/oauth/
:test-group-users:                  {test-api-client-group}/users/

// DATA Package Directories
:data-basedir: ../../data/

//  slack-jackson-dto
:slack-jackson-dto-basedir:         {data-basedir}/slack-jackson-dto/src/main/kotlin/io/olaph/slack/dto/jackson/
:dto-group:                         {slack-jackson-dto-basedir}/group/

:dto-group-auth:                    {dto-group}/auth/
:dto-group-channels:                {dto-group}/channels/
:dto-group-chat:                    {dto-group}/chat/
:dto-group-conversations:           {dto-group}/conversations/
:dto-group-dialog:                  {dto-group}/dialog/
:dto-group-im:                      {dto-group}/im/
:dto-group-interactive_component:   {dto-group}/interactive_component/
:dto-group-oauth:                   {dto-group}/oauth/
:dto-group-users:                   {dto-group}/users/


//  slack-jackson-dto-extensions
:dto-test-extensions-basedir:       {data-basedir}/slack-jackson-dto-test-extensions/src/main/kotlin/io/olaph/slack/dto/jackson/
:dto-test-group:                    {dto-test-extensions-basedir}/group/

:dto-test-group-auth:               {dto-test-group}/auth/
:dto-test-group-channels:           {dto-test-group}/channels/
:dto-test-group-chat:               {dto-test-group}/chat/
:dto-test-group-dialog:             {dto-test-group}/dialog/
:dto-test-group-users:              {dto-test-group}/users/


= Olaph.io Spring Boot Framework for Slack

=== Description
..

=== Motivation
..

---

= Getting Started

These steps are required in order to start writing your first Slack App.

=== Creating a Slack App

Go to https://api.slack.com/
Under "Your Apps" create a new Slack App, give it a name and select the Developement Slack Workspace for it.

Now you will need to set-up your App on the Slack API page.

At this point you might need to use a service like ngrok or any other tunneling software in order to enable forwarding to your local environment.

=== Configuration of your Slack App

It is necessary to activate the Incoming Webhooks. This is required in order to enable the installation process of your App later on.

Head over to the Interactive Components, activate that feature and enter your desired Request URL.
(e.g. https://samplebot.eu.ngrok.io/interactive-components

Go to Slash Commands and create a new command. This sample project implements a basic Ping command, wich will respond with a Pong chat message.

The command needs to have a Request URL just like the interactive components (e.g. https://samplebot.eu.ngrok.io/commands

For our sample project we need to add Bot Event Subscriptions so that our sample bot can at least read incoming instant messages.

Before you can do that you need to add a Bot User (with a display name and default username)

Enable Events and add message.im to your Bot Events. This will enable the bot to react on messages that are sent via private channels (direct messages).

When everything is set up you can add the App to a Workspace under OAuth & Permissions.

After you added your App to a Workspace you'll see a OAuth Access Token and a Bot User OAuth Access Token.
These will be required in later steps in order to interact with the Slack API.

=== Writing the App

Create a new Gradle project and insert the build.gradle file that you have to generate using https://start.spring.io/ with following options:
Project: Gradle Project
Language: Kotlin
Packaging: Jar
Java Version: 8
Dependencies: Web



Project meta data can be chosen as you like (but should follow common conventions for group-naming and packaging)
The Spring Starter zip-file has to be extracted and the gradle build file should be placed in your project root file. Move the src folder contents considering the intern packaging folders to your kotlin main path in the projects src folder.

Ultimatively you'll find your Applikation.kt (name can differ) with your main function in that folder and you're all set to run your application.
Your ressources folder should contain the application.properties file with a logging directive and should contain this for the beginning:


Now that you have the SampleApplication running you can start adding a Command-Receiver.

In this example we are using a simple ping command.

First, you'll need a Command Receiver, let's name it PingCommandReceiver.
This receiver implements the SlashCommandReceiver Interface and you need to override the supportsCommand and onReceiveSlashCommand functions.

The supportsCommand-function returns a Boolean: True if the underlying CommandBroker @RestController recognizes the command-String of our SlackCommand Data Class.
Since our CommandBroker has a @PostMapping-Annoation it's basically listening for every command that is posted to the /commands endpoint.

In the end we want to send a simple "Pong!"-Message with our onReceiveSlashCommand so it would be a good practice to have a separate
Service for that.


// ADD LATER
//Let's create a SlackSendPongService for that and use it in our @Autowired constructor of the PingCommandReceiver.



== Structure
The basic structure of this project consists of Broker, Client and Data packages.

=== Broker
The broker packages is divided in broker, configuration, exception and receiver packages.

==== broker
..

==== configuration
..


==== exception
..


==== receiver
..


=== Client

==== Slack API Client

Interfaces containing declarations for the abstract classes for the later implementation inside the implementation-package.
See <<Spring API Client>>

==== Spring API Client

Default implementations for the Slack Api Client interfaces.

==== Spring API Client Tests

Testing the functionality of the implementations using Mockito and JUnit5

=== Data

==== Data Classes

Data classes in compliance the Slack API

==== Extension Functions

Extensions on Data Classes for better testing using sample functions.

== License

== Contact